    [build]
      command = "npm install --legacy-peer-deps && npm run build"
      publish = "build"

    [build.environment]
      NODE_VERSION = "20"
      # PYTHON_VERSION = "3.9" # We'll try commenting this out first
    