    [build]
      command = "npm install && npm run build"
      publish = "build"

    [build.environment]
      NODE_VERSION = "20"
      NPM_FLAGS = "--legacy-peer-deps"
      # PYTHON_VERSION = "3.9" # Keep this commented out unless a Python error explicitly reappears
    